service: backend
runtime: python39
entrypoint: gunicorn -w 2 app:app
instance_class: F4

env_variables:
  TF_CPP_MIN_LOG_LEVEL: "2"

handlers:
  - url: /static
    static_dir: static/

  - url: /.*
    script: auto
